### ISSUE TITLE
Add (or move) parse_datetime to module Astro::Montenbruck::Time.pm

### ISSUE THREAD

**Issue by tbrowder** [skrushinsky/astro-montenbruck#11]

**Comment by skrushinsky** [comment]
Well, my original intention was to keep the core library, including `Astro::Montenbruck::Time`, as lite as possible, so that it can be integrated to other software with minimal dependencies. At the other hand, parsing and formatting routines are subjects of change. Currently, they depend on `DateTime`  library, which is considered by many developers an unwanted dependency. That's why I keep them in a separate package, which sooner or later will be refactored or even moved to another project. Actually, date parsing may be done by many means, depending on application requirements.

**Comment by tbrowder** [comment]
Okay, thanks.
